name: Build and Run QEMU

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libpixman-1-dev zlib1g-dev libglib2.0-dev ninja-build qemu-system-misc opensbi u-boot-qemu qemu-utils axel

    - name: Download QEMU
      run: |
        wget https://download.qemu.org/qemu-8.2.2.tar.xz
        tar xf qemu-8.2.2.tar.xz

    - name: Build QEMU
      run: |
        cd qemu-8.2.2
        ./configure --target-list=riscv64-softmmu,riscv64-linux-user --prefix=/usr --enable-user --enable-linux-user --enable-slirp
        make

    - name: Install QEMU
      run: |
        cd qemu-8.2.2
        sudo make install

    - name: Verify QEMU installation
      run: |
        qemu-system-riscv64 --version
        qemu-system-riscv64 -netdev help

    - name: Download Ubuntu for RISC-V
      run: |
        axel -n 16 https://niconiconi.us/ubuntu-22.04.4-preinstalled-server-riscv64+unmatched.img

    - name: Run Ubuntu in QEMU (in background)
      run: |
        qemu-system-riscv64 \
          -machine virt -nographic -m 5000 -smp 2 \
          -kernel /usr/lib/u-boot/qemu-riscv64_smode/uboot.elf \
          -device virtio-net-device,netdev=eth0 -netdev user,id=eth0,hostfwd=tcp::2222-:22 \
          -device virtio-rng-pci \
          -cpu rv64,v=true,vlen=256,vext_spec=v1.0 \
          -drive file=ubuntu-22.04.4-preinstalled-server-riscv64+unmatched.img,format=raw,if=virtio &
          sleep 150
      
    - name: SSH into the QEMU instance
      run: |
        sshpass -p 'niconi' ssh -o StrictHostKeyChecking=no root@127.0.0.1 -p 2222
        sudo apt-get update
        sudo apt-get install -y build-essential python3-dev python3-setuptools python3-pip libatlas-base-dev gfortran
        git clone https://github.com/xianyi/OpenBLAS.git
        cd OpenBLAS
        make HOSTCC=gcc TARGET=x280 NUM_THREADS=8 CC=riscv64-unknown-linux-gnu-clang FC=riscv64-unknown-linux-gnu-gfortran
        sudo make install
        cd
        git clone https://github.com/numpy/numpy.git

      env:
        SSHPASS: niconi